SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refund_status VARCHAR(30) DEFAULT NULL AFTER admin_notes', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refund_status');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refund_reference VARCHAR(120) DEFAULT NULL AFTER refund_status', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refund_reference');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refund_amount DECIMAL(12,2) DEFAULT NULL AFTER refund_reference', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refund_amount');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refund_error TEXT DEFAULT NULL AFTER refund_amount', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refund_error');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refund_payload LONGTEXT DEFAULT NULL AFTER refund_error', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refund_payload');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := (SELECT IF(COUNT(*) = 0, 'ALTER TABLE return_requests ADD COLUMN refunded_at DATETIME DEFAULT NULL AFTER refund_payload', 'SELECT 1') FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'return_requests' AND COLUMN_NAME = 'refunded_at');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
